# Generated by Django 3.1.7 on 2021-03-15 01:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangareader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangalist',
            name='author',
            field=models.ForeignKey(default=datetime.datetime(2021, 3, 15, 1, 24, 24, 34548, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangalist',
            name='body',
            field=models.TextField(default=datetime.datetime(2021, 3, 15, 1, 24, 40, 295142, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mangalist',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
